rbac:
  create: true
  readSecrets: true
serviceAccount:
  create: false
  name: jenkins-service-account
controller:
  ingress:
    enabled: enabled
  containerEnvFrom:
    - secretRef:
        name: jenkinsoauth
