rbac:
  create: true
  readSecrets: true
serviceAccount:
  create: false
  name: jenkins-service-account
controller:
  ingress:
    enabled: enabled
    paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - backend:
          serviceName: jenkins
          servicePort: 8080
  containerEnvFrom:
    - secretRef:
        name: jenkinsoauth
